# Generated by Django 5.2.17 on 2026-08-13 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backups', '0005_backup_backups_device__bc4cd2_idx_and_more'),
        ('devices', '0009_device_ssh_host_key_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('device_filters', models.JSONField(blank=True, default=dict)),
                ('rules', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_policies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Policy',
                'verbose_name_plural': 'Compliance Policies',
                'db_table': 'compliance_policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_index', models.IntegerField(help_text='Index into policy.rules — identifies which rule this is')),
                ('rule_description', models.TextField(help_text='Snapshot of the rule description at detection time')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(blank=True, help_text='The backup that was checked when this violation was last (re)detected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_violations', to='backups.backup')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_violations', to='devices.device')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='compliance.compliancepolicy')),
            ],
            options={
                'verbose_name': 'Compliance Violation',
                'verbose_name_plural': 'Compliance Violations',
                'db_table': 'compliance_violations',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status', '-detected_at'], name='compliance__status_bb2571_idx'), models.Index(fields=['policy', 'device', 'rule_index'], name='compliance__policy__ecf92a_idx')],
                'unique_together': {('policy', 'device', 'rule_index')},
            },
        ),
    ]
