# Generated by Django 5.2.8 on 2025-11-29 15:18

from django.db import migrations, models


def migrate_old_themes(apps, schema_editor):
    """Migrate old theme values to new ones"""
    User = apps.get_model('accounts', 'User')

    # Mapping old theme names to new ones
    theme_mapping = {
        'neumorphism': 'light',
        'industrial': 'dark_blue',
        'isometric': 'teal_light',
        'glassmorphism': 'light',
        'blueprint': 'deep_dark',
    }

    for old_theme, new_theme in theme_mapping.items():
        User.objects.filter(theme=old_theme).update(theme=new_theme)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog_audit_logs_action_f48619_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_old_themes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark_blue', 'Dark Blue'), ('teal_light', 'Teal Light'), ('deep_dark', 'Deep Dark')], default='light', max_length=20),
        ),
    ]
