# Generated by Django 5.2.8 on 2025-12-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_theme_to_new_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_size',
            field=models.IntegerField(choices=[(20, '20'), (50, '50'), (100, '100')], default=50),
        ),
    ]
