# Generated by Django 5.2.17 on 2026-08-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_scope',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
