# Generated by Django 5.2.17 on 2026-08-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_device_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='User-facing label, e.g. "YubiKey" or "MacBook Touch ID"', max_length=100)),
                ('credential_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.BigIntegerField(default=0, help_text='Authenticator-reported use counter — a non-increasing value on a future login flags a possibly cloned authenticator.')),
                ('transports', models.JSONField(blank=True, default=list, help_text='e.g. ["usb", "nfc", "internal"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'db_table': 'webauthn_credentials',
                'ordering': ['-created_at'],
            },
        ),
    ]
