# Generated by Django 5.2.8 on 2025-11-14 03:44

from django.db import migrations


def populate_vendor_commands(apps, schema_editor):
    """Populate backup_commands for predefined vendors"""
    Vendor = apps.get_model('devices', 'Vendor')

    # Vendor backup commands with setup, backup command, and enable_mode flag
    vendor_commands = {
        'cisco': {
            'setup': ['terminal length 0'],
            'backup': 'show running-config',
            'enable_mode': True
        },
        'cisco-ios': {
            'setup': ['terminal length 0'],
            'backup': 'show running-config',
            'enable_mode': True
        },
        'cisco-nxos': {
            'setup': ['terminal length 0'],
            'backup': 'show running-config',
            'enable_mode': True
        },
        'cisco-xr': {
            'setup': ['terminal length 0'],
            'backup': 'show running-config',
            'enable_mode': True
        },
        'juniper': {
            'setup': ['cli', 'set cli screen-length 0'],
            'backup': 'show configuration',
            'enable_mode': False
        },
        'huawei': {
            'setup': ['screen-length 0 temporary'],
            'backup': 'display current-configuration',
            'enable_mode': False
        },
        'hp': {
            'setup': ['terminal length 1000'],
            'backup': 'show running-config',
            'enable_mode': True
        },
        'arista': {
            'setup': ['terminal length 0'],
            'backup': 'show running-config',
            'enable_mode': True
        },
        'mikrotik': {
            'setup': [],
            'backup': '/export',
            'enable_mode': False
        },
        'fortinet': {
            'setup': ['config system console', 'set output standard', 'end'],
            'backup': 'show full-configuration',
            'enable_mode': False
        },
        'ubiquiti': {
            'setup': ['terminal length 0'],
            'backup': 'show configuration',
            'enable_mode': False
        },
        'grandstream': {
            'setup': ['terminal length 1000'],
            'backup': 'show running-config',
            'enable_mode': True
        },
        'dell': {
            'setup': ['terminal length 0'],
            'backup': 'show running-config',
            'enable_mode': True
        },
        'zyxel': {
            'setup': ['terminal length 0'],
            'backup': 'show running-config',
            'enable_mode': False
        },
        'dlink': {
            'setup': ['terminal length 512'],
            'backup': 'show config current_config',
            'enable_mode': False
        },
        'tplink': {
            'setup': ['terminal length 0'],
            'backup': 'show running-config',
            'enable_mode': False
        },
        'extreme': {
            'setup': ['disable clipaging'],
            'backup': 'show configuration',
            'enable_mode': False
        },
        'a10-networks': {
            'setup': ['terminal paging off'],
            'backup': 'show running-config',
            'enable_mode': True
        },
    }

    for slug, commands in vendor_commands.items():
        try:
            vendor = Vendor.objects.get(slug=slug)
            vendor.backup_commands = commands
            vendor.save()
            print(f"Updated backup commands for vendor: {vendor.name}")
        except Vendor.DoesNotExist:
            print(f"Vendor with slug '{slug}' not found, skipping")


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_vendor_commands, migrations.RunPython.noop),
    ]
