# Generated by Django 5.2.8 on 2025-11-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicegroup',
            name='color',
            field=models.CharField(choices=[('#6366f1', 'Indigo'), ('#8b5cf6', 'Violet'), ('#ec4899', 'Pink'), ('#ef4444', 'Red'), ('#f97316', 'Orange'), ('#eab308', 'Yellow'), ('#22c55e', 'Green'), ('#14b8a6', 'Teal'), ('#3b82f6', 'Blue'), ('#64748b', 'Slate')], default='#6366f1', max_length=7),
        ),
    ]
