# Generated by Django 5.2.8 on 2025-11-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_remove_device_groups'),
        ('devices', '0005_add_color_to_devicegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='group',
        ),
        migrations.DeleteModel(
            name='DeviceGroup',
        ),
    ]
