# Generated by Django 5.2.8 on 2025-11-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_device_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='custom_commands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='device',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
