# Generated by Django 5.2.8 on 2025-12-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_custom_commands_alter_device_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='devicecredential',
            name='password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
