# Generated by Django 4.2.9 on 2026-08-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_allow_empty_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ssh_host_key_fingerprint',
            field=models.CharField(blank=True, help_text='SHA256 fingerprint of the pinned host key', max_length=128),
        ),
        migrations.AddField(
            model_name='device',
            name='ssh_host_key_pending_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='ssh_host_key_pending_fingerprint',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='device',
            name='ssh_host_key_pending_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='ssh_host_key_type',
            field=models.CharField(blank=True, help_text='e.g. ssh-ed25519, ssh-rsa', max_length=32),
        ),
        migrations.AddField(
            model_name='device',
            name='ssh_host_key_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the current key was pinned/approved', null=True),
        ),
    ]
