# Generated by Django 5.2.8 on 2025-11-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_add_schedule_to_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupschedule',
            name='device_group',
        ),
    ]
