# Generated by Django 5.2.8 on 2025-11-22 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_remove_device_groups'),
        ('devices', '0006_remove_device_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='backup',
            index=models.Index(fields=['device', 'success', '-created_at'], name='backups_device__bc4cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['is_active', 'next_run'], name='backup_sche_is_acti_65256c_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['is_active', 'frequency'], name='backup_sche_is_acti_f3a30d_idx'),
        ),
    ]
